### PR TITLE
Make derive work for all primes. Fixes #84.

### LINKED ISSUE #84: ff_derive fails with no sqrt for p = 5 (mod 8) and p = 9 (mod 16)
The `ff_derive` derived `PrimeField` implementation fails to derive a sqrt function for primes `p = 5 (mod 8)` and `p = 9 (mod 16)`, resulting in a compile-time error for these cases.  According to the introduction of [IACR Preprint 2012/685](https://eprint.iacr.org/2012/685) (the cited reference for the algorithms used for the `p = 3 (mod 4)` and `p = 1 (mod 16)` cases), efficient algorithms do exist for computing square roots over these primes; however, these algorithms are not currently implemented here.

In Issue #33, this limitation is noted explicitly, so it may be that the desired use cases for this library don't require full coverage of odd primes.  I just wanted to check whether this is an intentional omission for maintainability, or if it's simply a feature that hasn't been added yet.  If it's the latter and maintainers are interested, I might be able to assemble a pull request.

### PR DESCRIPTION
**Pull request by VictorArcium**
Derive failed for some primes because the `sqrt` function derivation failed. This PR makes `derive` work for all primes.

This fixes #84

### CODE REVIEW

**Review by str4d — APPROVED** [review]
utACK f5cbd49d64e51c893f7119e0fed66ea49bacc878. On a re-reading of https://eprint.iacr.org/2012/685 Section IV B 3, I agree that it can be used for `p = 1 (mod 4)`, not just `p = 1 (mod 16)`.

File: ff_derive/src/lib.rs [hunk 1]
```diff
@@ -538,7 +538,7 @@ fn prime_field_constants_and_sqrt(
             };
 
             quote! {
-                // Tonelli-Shank's algorithm for q mod 16 = 1
+                // Tonelli-Shank's algorithm works for every odd prime.
```
Comment (daira) [inline ff_derive/src/lib.rs:541]: This should say: "Tonelli-Shank's algorithm works for every remaining odd prime (i.e. q = 1 (mod 4))."
